# -*- coding: utf-8 -*-
"""Gemini_api_with_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9Y6KfNTE3yXR2_ak90kI5ihtjV4ox2y
"""

! pip install -q -U google-generativeai

"""### Import packages

"""

import google.generativeai as palm
import pathlib
import textwrap
from IPython.display import display
from IPython.display import Markdown
import google.generativeai as genai

def to_markdown(text):
  text=text.replace('.',' *')
  return Markdown(textwrap.indent(text,'>',predicate= lambda _:True))

  # Example usage

input_text=" this is a . simple text with point"
result=to_markdown(input_text)


display(result)

"""Setup API Key"""

from google.colab import userdata

GOOGLE_API_KEY=userdata.get('googleapikey')

genai.configure(api_key=GOOGLE_API_KEY)

for model in genai.list_models():
  print(model)

for model in genai.list_models():
  if 'generateContent' in model.supported_generation_methods:
    print(model.name)

"""### generate text from text"""

model=genai.GenerativeModel('gemini-pro')

# Commented out IPython magic to ensure Python compatibility.
# %%time
# response=model.generate_content('what is the meaning of life')

response.text

to_markdown(response.text)

response.candidates

response.parts

response.prompt_feedback

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# response=model.generate_content("whst is meaning of life ?",stream=True)
# for chunk in response:
#   print(chunk.text)
#   print("_"*80)

"""### generate text from image"""

!curl-o image2.jpg https://tse4.mm.bing.net/th?id=OIP.2ipyciZc3yjfiBePI2p0QAHaF6&pid=Api&P=0&h=220